### ISSUE TITLE
Code not getting compiled package "io.liftbridge.proto" not found!

### ISSUE THREAD

**Issue by akshay071990** [caioaao/java-liftbridge#7]
After downloading the source code, gradle build is reporting error "package io.liftbridge.proto not found " Compile error.
Can anyone pls commit this missing package!

**Comment by tylertreat** [comment]
How are you building the client? It should work with:

```
./gradlew build
```

It should also build in an IDE such as IntelliJ. Can you verify the liftbridge-api submodule folder is present when you cloned the repo? That contains protobuf that gets generated as part of the build.

**Comment by akshay071990** [comment]
Hi Tyler,

Thanks for responding.

Yes i am running ./gradlew build and when i execute i get the below error:
Task :compileJava FAILED/Users/akshaymarali/Documents/NATS/LiftBridge/JAVA/java-liftbridge/src/main/java/io/liftbridge/Message.java:3: error: package io.liftbridge.proto does not existimport io.liftbridge.proto.Api;

Also, has it to do anything with the gradle version? i also see the below warning :> 
Task :generateProto UP-TO-DATEProperty 'buildType' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.Property 'builtins' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
About liftbridge-api  folder, yes this is present when i cloned but the folder is empty.

**Comment by tylertreat** [comment]
Sounds like the submodule hasn't been initialized. Try running the following from the root project directory:

```
git submodule update --init
```

**Comment by akshay071990** [comment]
Hi Tyler,

I am getting the below permission issue when i execute "git submodule update --init":
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:liftbridge-io/liftbridge-api.git' into submodule path '/Users/akshaymarali/Documents/NATS/LiftBridge/JAVA/java-liftbridge/liftbridge-api' failed
Failed to clone 'liftbridge-api' a second time, aborting

**Comment by tylertreat** [comment]
How did you originally clone the java-liftbridge repo, with SSH or HTTPS?

**Comment by akshay071990** [comment]
Hi Tyler,

Cloned with HTTPS.


Thx
Akshay

**Comment by tylertreat** [comment]
I think the issue is related to git trying to fetch the submodule via SSH. If you don't have SSH setup with git, you can modify the submodule to fetch over HTTPS: https://stackoverflow.com/questions/11410017/git-submodule-update-over-https

**Comment by akshay071990** [comment]
HI Tyler,

Somehow it did not worked for me with HTTPS after my SSH Setup now i am not facing any issues, Thanks for all your help!

I have one last doubt **the subscriber example w.r.t GOLANG client will listen forever to the stream**! 
But with the below Java client i am not able to achieve ( even if i modify the lambda function it gets the program gets terminated after few secons) **can u pls help as how my subscriber in java can listen forever to a stream**:
```
public static void testSubscribeFromBeginning() throws NoSuchPartitionException {
        SubscriptionOptions opts = new SubscriptionOptions().startAtEarliestReceived();
        final List<Character> streamValues = new ArrayList<>();

        Subscription sub = client.subscribe("tempstream", opts, new MessageHandler() {
            public void onMessage(io.liftbridge.Message msg) {
            String output = new String(msg.getValue(), StandardCharsets.UTF_8);
            	System.out.println(output);
                streamValues.add(ByteBuffer.wrap(msg.getValue()).getChar());
            }

            public void onError(Throwable t) {
                fail(t.getMessage());
            }
        });
 await().atMost(15, SECONDS).until(() -> streamValues.size() >= 20);
        sub.unsubscribe();
    }
```

**Comment by tylertreat** [comment]
The above test is designed to terminate because of:

```java
await().atMost(15, SECONDS).until(() -> streamValues.size() >= 20);
```

This is waiting to receive 20 messages from the stream and then exits. However, `subscribe` is not a _blocking_ call, it is asynchronous. So if you want your process to block, you will need to subscribe and then block the thread, e.g. `Thread.sleep(Long.MAX_VALUE);`.

**Comment by akshay071990** [comment]
Hi Tyler,

got it thanks for resolving the issue 👍
